{{- if .Values.externalSecret.enabled }}
{{- range .Values.externalSecret.secrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ $.Values.externalSecret.secretStoreName }}
  target:
    name: {{ .name }}
    creationPolicy: Owner
    deletionPolicy: Retain
{{- if .dataFrom }}
  dataFrom:
    - extract:
        key: {{ .dataFrom.key }}
{{- else }}
  data:
{{- range .data }}
    - secretKey: {{ .secretKey | default .keyName }}
      remoteRef:
        key: {{ .keyName }}
        conversionStrategy: Default
        decodingStrategy: None
{{- end }}
{{- end }}
{{- end }}
{{- end }}
